# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Voa24t51PgvakM5VYMCmEM3Lsq3RKMiX
"""

from google.colab import files
uploaded=files.upload()

!pip install pandas
import pandas as pd
d=pd.read_csv('Balaji Fast Food Sales.csv')
d

d.isnull().sum()

d.duplicated().sum()

d['date'] = pd.to_datetime(d['date'], dayfirst=True, errors='coerce')
d['date'] = d['date'].dt.strftime('%d-%m-%Y')

d



d.isnull().sum()

d['transaction_type'] = d['transaction_type'].fillna(d['transaction_type'].mode()[0])

d.isnull().sum()

x=d[d['item_price'].isnull()]
y=d[~d['item_price'].isnull()]

x

y

d.groupby('item_name')['item_price'].mean()

def ad(x):
  if x=='Aalopuri':
    return 20
  elif x=='Cold coffee':
    return 40
  elif x=='Frankie':
    return 50
  elif x=='Sandwich':
    return 60
  elif x=='Sugarcane juice':
    return 25
  elif x=='Vadapav':
    return 20
  else:
    return 20

x['item_price']=x['item_name'].apply(ad)

x

df=pd.concat((x,y),ignore_index=True)
df

df.isnull().sum()

x=df[df['item_type'].isnull()]
y=df[~df['item_type'].isnull()]

x

y

def da(x):
  if x=='Aalopuri':
    return 'Fastfood'
  elif x=='Cold coffee':
    return 'Beverages'
  elif x=='Frankie':
    return 'Fastfood'
  elif x=='Sandwich':
    return 'Fastfood'
  elif x=='Sugarcane juice':
    return 'Beverages'
  elif x=='Vadapav':
    return 'Fastfood'
  else:
    return 'Fastfood'

x['item_type']=x['item_name'].apply(da)

x

final=pd.concat((x,y),ignore_index=True)
final

final.isnull().sum()



final.to_csv('Sales cleaned_data.csv', index=False)
files.download('Sales cleaned_data.csv')

